# Generated by Django 5.2.6 on 2025-10-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_perfil_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
