# Generated by Django 5.2.6 on 2025-10-07 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('es_documento', models.BooleanField(default=False)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijas', to='procesos.carpetaproceso')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_proceso', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('SIN', 'Sin empezar'), ('CUR', 'En curso'), ('FIN', 'Finalizado'), ('OBS', 'Observación'), ('CAM', 'Cambio de abogado'), ('CA', 'Casación')], default='SIN', max_length=3)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='procesos.carpetaproceso')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='procesos.carpetaproceso')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('carpeta', 'nombre', 'version')},
            },
        ),
    ]
