# Generated by Django 5.2.6 on 2025-10-08 03:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoproceso',
            options={'ordering': ['-creado_en', '-id']},
        ),
        migrations.AddField(
            model_name='documentoproceso',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoproceso',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
