# Generated by Django 5.2.6 on 2025-10-17 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_alter_documentoproceso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='carpeta_documentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_documentales', to='procesos.carpetaproceso', verbose_name='Carpeta documental (auto)'),
        ),
    ]
